version: '3'
services:
    api:
        build:
            context: .
            dockerfile: Dockerfile
        image: 'app-node'
        container_name: app-node
        restart: always
        environment: 
            DB_IP_HOST: ${DB_IP_HOST}
            DB_PORT: 3306
        ports:
            - '8000:8000'
        command: > 
            bash -c "python wait-host-container.py $${DB_IP_HOST} $${DB_PORT}
            && npx sequelize db:create
            && npx sequelize db:migrate
            && npx sequelize db:seed:all
            && node server.js"
    db:
        image: 'mysql:5.7'
        container_name: express_sequelize
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
        ports:
            - '3306:3306'