version: '3'
services:
    api:
        build:
            context: .
            dockerfile: Dockerfile
        image: 'app-node'
        container_name: app-node
        restart: always
        ports:
            - '8000:8000'
        command: bash -c "node index.js"
    db:
        image: 'mysql:5.7'
        container_name: express_sequelize
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: express_sequelize
        ports:
            - '3306:3306'